---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: NSM_CLUSTER_NAME
  region: NSM_REGION
  version: "1.27"

kubernetesNetworkConfig:
  ipFamily: IPv6

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy

iam:
  withOIDC: true

managedNodeGroups:
  - name: NSM_NODEGROUPS_NAME
    instanceType: t3.xlarge
    desiredCapacity: 2
